# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/genesys.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from api import asset_groups_pb2 as api_dot_asset__groups__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/genesys.proto',
  package='genesys',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x61pi/genesys.proto\x12\x07genesys\x1a\x16\x61pi/asset_groups.protob\x06proto3'
  ,
  dependencies=[api_dot_asset__groups__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
